{% set version = '0.0.13' %}

package:
  name: optlang_enumerator
  version: {{ version }}

source:
  url: https://github.com/cnapy-org/optlang_enumerator/archive/v{{ version }}.tar.gz
  sha256: fa45d0a2e1ad3a6a5aff7a3743442c97bc25ebcdd2bd15f92e5692db03ca929a

build:
  noarch: python
  number: 0  # NOTE: increment for new build/set to zero for new version
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.7,<3.11
  run:
    - python >=3.7,<3.11
    - numpy =1.23
    - scipy
    - optlang
    - cobra >=0.26.3
    - sympy >=1.12
    - efmtool_link >=0.0.8

test:
  imports:
    - optlang_enumerator
  requires:
    - pip
  commands:
    - pip check

about:
  home:  https://github.com/cnapy-org/optlang_enumerator
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: Enumeration of multiple solutions to a MILP with the optlang framework.
  doc_url: https://github.com/cnapy-org/optlang_enumerator
  dev_url: https://github.com/cnapy-org/optlang_enumerator

extra:
  recipe-maintainers:
    - axelvonkamp
