{% set version = "0.0.15" %}

package:
  name: optlang_enumerator
  version: {{ version }}

source:
  url: https://github.com/cnapy-org/optlang_enumerator/archive/v{{ version }}.tar.gz
  sha256: 6a7a470d0f6ef0115b8a24f85ec2c3bc98e4fb9c18bace3496737e241edf1cc6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<3.11
    - numpy =1.23
    - scipy
    - optlang
    - cobra >=0.26.3
    - sympy >=1.12
    - efmtool_link >=0.0.8

test:
  imports:
    - optlang_enumerator
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/cnapy-org/optlang_enumerator
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: Enumeration of multiple solutions to a MILP with the optlang framework.
  doc_url: https://github.com/cnapy-org/optlang_enumerator
  dev_url: https://github.com/cnapy-org/optlang_enumerator

extra:
  recipe-maintainers:
    - axelvonkamp
